const PRODUCTS = [
  {
    "id": 1,
    "handle": "dolce-gabbana-ripped-green-straight-jeans-1",
    "brand": "DOLCE & GABBANA",
    "title": "Ripped Green Straight Jeans",
    "price": 43.31,
    "compareAtPrice": 700.0,
    "size": "52",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p1.jpg",
    "description": "DOLCE & GABBANA — Ripped Green Straight Jeans. Vintage one-of-a-kind piece, in good condition. Size 52.",
    "drop": "Founding"
  },
  {
    "id": 2,
    "handle": "dsquared2-green-denim-cargo-pants-2",
    "brand": "DSQUARED2",
    "title": "Green Denim Cargo Pants",
    "price": 124.63,
    "compareAtPrice": 350.0,
    "size": "40",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p2.jpg",
    "description": "DSQUARED2 — Green Denim Cargo Pants. Vintage one-of-a-kind piece, in good condition. Size 40.",
    "drop": "Founding"
  },
  {
    "id": 3,
    "handle": "dsquared2-navy-casual-t-shirt-3",
    "brand": "DSQUARED2",
    "title": "Navy Casual T-Shirt",
    "price": 38.11,
    "compareAtPrice": 290.0,
    "size": "S",
    "category": "Tops",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p3.jpg",
    "description": "DSQUARED2 — Navy Casual T-Shirt. Vintage one-of-a-kind piece, in good condition. Size S.",
    "drop": "Founding"
  },
  {
    "id": 4,
    "handle": "catarina-martins-tricolor-cowboy-boots-4",
    "brand": "CATARINA MARTINS",
    "title": "Tricolor Cowboy Boots",
    "price": 147.8,
    "compareAtPrice": 280.0,
    "size": "37",
    "category": "Footwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p4.jpg",
    "description": "CATARINA MARTINS — Tricolor Cowboy Boots. Vintage one-of-a-kind piece, in good condition. Size 37.",
    "drop": "Founding"
  },
  {
    "id": 5,
    "handle": "dsquared2-blue-distressed-denim-jeans-5",
    "brand": "DSQUARED2",
    "title": "Blue Distressed Denim Jeans",
    "price": 70.81,
    "compareAtPrice": 450.0,
    "size": "M",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p5.jpg",
    "description": "DSQUARED2 — Blue Distressed Denim Jeans. Vintage one-of-a-kind piece, in good condition. Size M.",
    "drop": "Founding"
  },
  {
    "id": 6,
    "handle": "dsquared2-black-strap-mini-dress-6",
    "brand": "DSQUARED2",
    "title": "Black Strap Mini Dress",
    "price": 42.28,
    "compareAtPrice": 550.0,
    "size": "42",
    "category": "Dresses",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p6.jpg",
    "description": "DSQUARED2 — Black Strap Mini Dress. Vintage one-of-a-kind piece, in good condition. Size 42.",
    "drop": "Founding"
  },
  {
    "id": 7,
    "handle": "plein-sud-blue-distressed-denim-jeans-7",
    "brand": "PLEIN SUD",
    "title": "Blue Distressed Denim Jeans",
    "price": 14.72,
    "compareAtPrice": 150.0,
    "size": "27",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p7.jpg",
    "description": "PLEIN SUD — Blue Distressed Denim Jeans. Vintage one-of-a-kind piece, in good condition. Size 27.",
    "drop": "Founding"
  },
  {
    "id": 8,
    "handle": "helmut-lang-straight-jeans-8",
    "brand": "HELMUT LANG",
    "title": "Straight Jeans",
    "price": 57.37,
    "compareAtPrice": 405.0,
    "size": "S",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p8.jpg",
    "description": "HELMUT LANG — Straight Jeans. Vintage one-of-a-kind piece, in good condition. Size S.",
    "drop": "Founding"
  },
  {
    "id": 9,
    "handle": "dsquared2-straight-jeans-9",
    "brand": "DSQUARED2",
    "title": "Straight Jeans",
    "price": 39.74,
    "compareAtPrice": 450.0,
    "size": "42",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p9.jpg",
    "description": "DSQUARED2 — Straight Jeans. Vintage one-of-a-kind piece, in good condition. Size 42.",
    "drop": "Founding"
  },
  {
    "id": 10,
    "handle": "dsquared2-formal-dress-10",
    "brand": "DSQUARED2",
    "title": "Formal Dress",
    "price": 397.44,
    "compareAtPrice": 890.0,
    "size": "40",
    "category": "Dresses",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p10.jpg",
    "description": "DSQUARED2 — Formal Dress. Vintage one-of-a-kind piece, in good condition. Size 40.",
    "drop": "Founding"
  },
  {
    "id": 11,
    "handle": "plein-sud-formal-dress-11",
    "brand": "PLEIN SUD",
    "title": "Formal Dress",
    "price": 99.36,
    "compareAtPrice": 210.0,
    "size": "38",
    "category": "Dresses",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p11.jpg",
    "description": "PLEIN SUD — Formal Dress. Vintage one-of-a-kind piece, in good condition. Size 38.",
    "drop": "Founding"
  },
  {
    "id": 12,
    "handle": "dsquared2-skinny-jeggings-12",
    "brand": "DSQUARED2",
    "title": "Skinny Jeggings",
    "price": 155.97,
    "compareAtPrice": 690.0,
    "size": "40",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p12.jpg",
    "description": "DSQUARED2 — Skinny Jeggings. Vintage one-of-a-kind piece, in good condition. Size 40.",
    "drop": "Founding"
  },
  {
    "id": 13,
    "handle": "dsquared2-hat-13",
    "brand": "DSQUARED2",
    "title": "Hat",
    "price": 105.99,
    "compareAtPrice": 175.0,
    "size": "One Size",
    "category": "Accessories",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p13.jpg",
    "description": "DSQUARED2 — Hat. Vintage one-of-a-kind piece, in good condition. Size One Size.",
    "drop": "Founding"
  },
  {
    "id": 14,
    "handle": "dsquared2-shoes-14",
    "brand": "DSQUARED2",
    "title": "Shoes",
    "price": 223.99,
    "compareAtPrice": 898.0,
    "size": "37",
    "category": "Footwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p14.jpg",
    "description": "DSQUARED2 — Shoes. Vintage one-of-a-kind piece, in good condition. Size 37.",
    "drop": "Founding"
  },
  {
    "id": 15,
    "handle": "dsquared2-sweatshirt-15",
    "brand": "DSQUARED2",
    "title": "Sweatshirt",
    "price": 173.99,
    "compareAtPrice": 320.0,
    "size": "S",
    "category": "Outerwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p15.jpg",
    "description": "DSQUARED2 — Sweatshirt. Vintage one-of-a-kind piece, in good condition. Size S.",
    "drop": "Founding"
  },
  {
    "id": 16,
    "handle": "dolce-gabbana-fluid-silk-t-shirt-16",
    "brand": "DOLCE & GABBANA",
    "title": "Fluid Silk T-Shirt",
    "price": 122.99,
    "compareAtPrice": 295.0,
    "size": "38",
    "category": "Tops",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p16.jpg",
    "description": "DOLCE & GABBANA — Fluid Silk T-Shirt. Vintage one-of-a-kind piece, in good condition. Size 38.",
    "drop": "Founding"
  },
  {
    "id": 17,
    "handle": "dsquared2-leather-vest-17",
    "brand": "DSQUARED2",
    "title": "Leather Vest",
    "price": 422.49,
    "compareAtPrice": 500.0,
    "size": "38",
    "category": "Outerwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p17.jpg",
    "description": "DSQUARED2 — Leather Vest. Vintage one-of-a-kind piece, in good condition. Size 38.",
    "drop": "Founding"
  },
  {
    "id": 18,
    "handle": "javier-simorra-skinny-fabric-trousers-18",
    "brand": "JAVIER SIMORRA",
    "title": "Skinny Fabric Trousers",
    "price": 1.36,
    "compareAtPrice": 140.0,
    "size": "38",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p18.jpg",
    "description": "JAVIER SIMORRA — Skinny Fabric Trousers. Vintage one-of-a-kind piece, in good condition. Size 38.",
    "drop": "Founding"
  },
  {
    "id": 19,
    "handle": "armani-light-jacket-19",
    "brand": "ARMANI",
    "title": "Light Jacket",
    "price": 44.15,
    "compareAtPrice": 550.0,
    "size": "S",
    "category": "Outerwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p19.jpg",
    "description": "ARMANI — Light Jacket. Vintage one-of-a-kind piece, in good condition. Size S.",
    "drop": "Founding"
  },
  {
    "id": 20,
    "handle": "dolce-gabbana-casual-skirt-20",
    "brand": "DOLCE & GABBANA",
    "title": "Casual Skirt",
    "price": 31.73,
    "compareAtPrice": 290.0,
    "size": "24",
    "category": "Skirts",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p20.jpg",
    "description": "DOLCE & GABBANA — Casual Skirt. Vintage one-of-a-kind piece, in good condition. Size 24.",
    "drop": "Founding"
  },
  {
    "id": 21,
    "handle": "helmut-lang-casual-skirt-21",
    "brand": "HELMUT LANG",
    "title": "Casual Skirt",
    "price": 32.22,
    "compareAtPrice": 400.0,
    "size": "S",
    "category": "Skirts",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p21.jpg",
    "description": "HELMUT LANG — Casual Skirt. Vintage one-of-a-kind piece, in good condition. Size S.",
    "drop": "Founding"
  },
  {
    "id": 22,
    "handle": "dsquared2-t-shirt-22",
    "brand": "DSQUARED2",
    "title": "T-Shirt",
    "price": 49.99,
    "compareAtPrice": 100.0,
    "size": "M",
    "category": "Tops",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p22.jpg",
    "description": "DSQUARED2 — T-Shirt. Vintage one-of-a-kind piece, in good condition. Size M.",
    "drop": "Founding"
  },
  {
    "id": 23,
    "handle": "helmut-lang-casual-dress-23",
    "brand": "HELMUT LANG",
    "title": "Casual Dress",
    "price": 24.26,
    "compareAtPrice": 259.9,
    "size": "M",
    "category": "Dresses",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p23.jpg",
    "description": "HELMUT LANG — Casual Dress. Vintage one-of-a-kind piece, in good condition. Size M.",
    "drop": "Founding"
  },
  {
    "id": 24,
    "handle": "dsquared2-skinny-jeggings-24",
    "brand": "DSQUARED2",
    "title": "Skinny Jeggings",
    "price": 28.79,
    "compareAtPrice": 200.0,
    "size": "38",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p24.jpg",
    "description": "DSQUARED2 — Skinny Jeggings. Vintage one-of-a-kind piece, in good condition. Size 38.",
    "drop": "Founding"
  },
  {
    "id": 25,
    "handle": "galliano-jacket-25",
    "brand": "GALLIANO",
    "title": "Jacket",
    "price": 76.01,
    "compareAtPrice": 600.0,
    "size": "S",
    "category": "Outerwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p25.jpg",
    "description": "GALLIANO — Jacket. Vintage one-of-a-kind piece, in good condition. Size S.",
    "drop": "Founding"
  },
  {
    "id": 26,
    "handle": "dolce-gabbana-casual-skirt-26",
    "brand": "DOLCE & GABBANA",
    "title": "Casual Skirt",
    "price": 57.57,
    "compareAtPrice": 400.0,
    "size": "L",
    "category": "Skirts",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p26.jpg",
    "description": "DOLCE & GABBANA — Casual Skirt. Vintage one-of-a-kind piece, in good condition. Size L.",
    "drop": "Founding"
  },
  {
    "id": 32,
    "handle": "armani-jacket-32",
    "brand": "ARMANI",
    "title": "Jacket",
    "price": 42.93,
    "compareAtPrice": 200.0,
    "size": "42",
    "category": "Outerwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p32.jpg",
    "description": "ARMANI — Jacket. Vintage one-of-a-kind piece, in good condition. Size 42.",
    "drop": "Founding"
  },
  {
    "id": 33,
    "handle": "balenciaga-sandals-33",
    "brand": "BALENCIAGA",
    "title": "Sandals",
    "price": 55.39,
    "compareAtPrice": 450.0,
    "size": "38",
    "category": "Footwear",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p33.jpg",
    "description": "BALENCIAGA — Sandals. Vintage one-of-a-kind piece, in good condition. Size 38.",
    "drop": "Founding"
  },
  {
    "id": 34,
    "handle": "just-cavalli-belt-34",
    "brand": "JUST CAVALLI",
    "title": "Belt",
    "price": 21.76,
    "compareAtPrice": 100.0,
    "size": "One Size",
    "category": "Accessories",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p34.jpg",
    "description": "JUST CAVALLI — Belt. Vintage one-of-a-kind piece, in good condition. Size One Size.",
    "drop": "Founding"
  },
  {
    "id": 35,
    "handle": "just-cavalli-belt-35",
    "brand": "JUST CAVALLI",
    "title": "Belt",
    "price": 25.84,
    "compareAtPrice": 100.0,
    "size": "One Size",
    "category": "Accessories",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p35.jpg",
    "description": "JUST CAVALLI — Belt. Vintage one-of-a-kind piece, in good condition. Size One Size.",
    "drop": "Founding"
  },
  {
    "id": 36,
    "handle": "armani-belt-36",
    "brand": "ARMANI",
    "title": "Belt",
    "price": 40.26,
    "compareAtPrice": 150.0,
    "size": "One Size",
    "category": "Accessories",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p36.jpg",
    "description": "ARMANI — Belt. Vintage one-of-a-kind piece, in good condition. Size One Size.",
    "drop": "Founding"
  },
  {
    "id": 37,
    "handle": "dsquared2-skinny-jeggings-37",
    "brand": "DSQUARED2",
    "title": "Skinny Jeggings",
    "price": 54.4,
    "compareAtPrice": 200.0,
    "size": "40",
    "category": "Bottoms",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p37.jpg",
    "description": "DSQUARED2 — Skinny Jeggings. Vintage one-of-a-kind piece, in good condition. Size 40.",
    "drop": "Founding"
  },
  {
    "id": 38,
    "handle": "armani-t-shirt-38",
    "brand": "ARMANI",
    "title": "T-Shirt",
    "price": 33.99,
    "compareAtPrice": 110.0,
    "size": "M",
    "category": "Tops",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p38.jpg",
    "description": "ARMANI — T-Shirt. Vintage one-of-a-kind piece, in good condition. Size M.",
    "drop": "Founding"
  },
  {
    "id": 39,
    "handle": "dior-t-shirt-39",
    "brand": "DIOR",
    "title": "T-Shirt",
    "price": 180.99,
    "compareAtPrice": 500.0,
    "size": "42",
    "category": "Tops",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p39.jpg",
    "description": "DIOR — T-Shirt. Vintage one-of-a-kind piece, in good condition. Size 42.",
    "drop": "Founding"
  },
  {
    "id": 41,
    "handle": "dolce-gabbana-t-shirt-41",
    "brand": "DOLCE & GABBANA",
    "title": "T-Shirt",
    "price": 60.49,
    "compareAtPrice": 200.0,
    "size": "38",
    "category": "Tops",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p41.jpg",
    "description": "DOLCE & GABBANA — T-Shirt. Vintage one-of-a-kind piece, in good condition. Size 38.",
    "drop": "Founding"
  },
  {
    "id": 42,
    "handle": "roberto-cavalli-t-shirt-42",
    "brand": "ROBERTO CAVALLI",
    "title": "T-Shirt",
    "price": 19.49,
    "compareAtPrice": 59.99,
    "size": "XS",
    "category": "Tops",
    "condition": "Great",
    "status": "in_stock",
    "image": "img/products/p42.jpg",
    "description": "ROBERTO CAVALLI — T-Shirt. Vintage one-of-a-kind piece, in good condition. Size XS.",
    "drop": "Founding"
  },
  {
    "id": 43,
    "handle": "gucci-pantalones-de-chandal-y-joggers-slouchy-seda-43",
    "brand": "GUCCI",
    "title": "Pantalones de chándal y joggers Slouchy Seda",
    "price": 621.49,
    "compareAtPrice": 1500.0,
    "size": "XXS",
    "category": "Bottoms",
    "condition": "Great",
    "status": "draft",
    "image": "img/products/placeholder.jpg",
    "description": "GUCCI — Pantalones de chándal y joggers Slouchy Seda. Secondhand one-of-a-kind piece, in good condition. Size XXS.",
    "drop": "Founding"
  }
];
